### ISSUE TITLE
Not working with has_many + through

### ISSUE THREAD

**Issue by chetanbissa27** [plentz/lol_dba#25]
```
Class: TrackLink
Association type: has_many
Association options: {:through=>:track_visits, :extend=>[]}
Exception: undefined method `klass' for nil:NilClass
/var/lib/gems/1.9.1/gems/lol_dba-1.6.0/lib/lol_dba.rb:121:in `block (2 levels) in check_for_indexes'
/var/lib/gems/1.9.1/gems/lol_dba-1.6.0/lib/lol_dba.rb:92:in `each_pair'
/var/lib/gems/1.9.1/gems/lol_dba-1.6.0/lib/lol_dba.rb:92:in `block in check_for_indexes'
/var/lib/gems/1.9.1/gems/lol_dba-1.6.0/lib/lol_dba.rb:88:in `each'
/var/lib/gems/1.9.1/gems/lol_dba-1.6.0/lib/lol_dba.rb:88:in `check_for_indexes'
/var/lib/gems/1.9.1/gems/lol_dba-1.6.0/lib/lol_dba.rb:190:in `simple_migration'
/var/lib/gems/1.9.1/gems/lol_dba-1.6.0/lib/tasks/lol_dba.rake:7:in `block (2 levels) in <top (required)>'
/var/lib/gems/1.9.1/gems/rake-10.1.0/lib/rake/task.rb:236:in `call'
/var/lib/gems/1.9.1/gems/rake-10.1.0/lib/rake/task.rb:236:in `block in execute'
/var/lib/gems/1.9.1/gems/rake-10.1.0/lib/rake/task.rb:231:in `each'
/var/lib/gems/1.9.1/gems/rake-10.1.0/lib/rake/task.rb:231:in `execute'
/var/lib/gems/1.9.1/gems/rake-10.1.0/lib/rake/task.rb:175:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/1.9.1/gems/rake-10.1.0/lib/rake/task.rb:168:in `invoke_with_call_chain'
/var/lib/gems/1.9.1/gems/rake-10.1.0/lib/rake/task.rb:161:in `invoke'
/var/lib/gems/1.9.1/gems/rake-10.1.0/lib/rake/application.rb:149:in `invoke_task'
/var/lib/gems/1.9.1/gems/rake-10.1.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/var/lib/gems/1.9.1/gems/rake-10.1.0/lib/rake/application.rb:106:in `each'
/var/lib/gems/1.9.1/gems/rake-10.1.0/lib/rake/application.rb:106:in `block in top_level'
/var/lib/gems/1.9.1/gems/rake-10.1.0/lib/rake/application.rb:115:in `run_with_threads'
/var/lib/gems/1.9.1/gems/rake-10.1.0/lib/rake/application.rb:100:in `top_level'
/var/lib/gems/1.9.1/gems/rake-10.1.0/lib/rake/application.rb:78:in `block in run'
/var/lib/gems/1.9.1/gems/rake-10.1.0/lib/rake/application.rb:165:in `standard_exception_handling'
/var/lib/gems/1.9.1/gems/rake-10.1.0/lib/rake/application.rb:75:in `run'
/var/lib/gems/1.9.1/gems/rake-10.1.0/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:19:in `load'
/usr/local/bin/rake:19:in `<main>'
```

**Comment by wpp** [comment]
I also ran into this today. But in my case the source of the [problem is in line 121](https://github.com/plentz/lol_dba/blob/master/lib/lol_dba.rb#L121).

Where `reflection_options.options[:through]` is a symbol `:participations` but the keys in `class_name.reflections.keys` are all strings `"participations"`.

I'm running Rails 4.2.0 and Ruby 2.2.0

**Comment by vraravam** [comment]
Same case with me. has_many with through, all calls (in the lol_dba.rb file) to any of the .reflections[] hash have to be accessed via string keys (ie adding .to_s) fixes the problem. Please fix asap!

**Comment by plentz** [comment]
Hey guys, grap 1.6.5 while it's hot. it should fix the problem. huge thanks to @wpp :)

**Comment by wpp** [comment]
@plentz glad I could help! Enjoy your weekend.

**Comment by PikachuEXE** [comment]
I am using rails `4.1.9`.

I have the same error again in `1.6.6`.
`1.6.4` runs fine without error but would cause #22 (of course).
`1.6.5` runs with same error AND cause #22.

**Comment by plentz** [comment]
@PikachuEXE can you please paste the error message?

**Comment by PikachuEXE** [comment]
@plentz sure:
http://pastebin.com/fLRR6mpc

**Comment by vraravam** [comment]
This would have been solved if my PR had got accepted :(

**Comment by plentz** [comment]
@PikachuEXE It's kinda hard just looking for that exception - I think it's something related to the namespaced models that you have. Could you do me a *huge* favor? Fork lol_dba, create a model that causes the exception(it can be a simplified one, not the entire copy of your model) here in `spec/fixtures` and make a pull request. You don't need to create the test or else, just the model that breaks lol_dba. With that in hands, I will code the fix and merge your PR.

@vraravam sorry, but not really. your pull request was breaking the tests, so if it got accepted, it would break more things :) - but I did a commit fixing some of those problems 104855c04f1169dcea98d402b05a3afcf6f7fd56

**Comment by vraravam** [comment]
Sorry - I didnt see the last 2 changed lines - my bad. The changes that I had done made all of my code to run - but, I didnt run the tests themselves (again my bad). Thanks for fixing. Is there a newer version of the gem with these latest changes? BTW - great gem!

**Comment by plentz** [comment]
@vraravam yup. I released version 1.6.6 yesterday, so you can give it a try :)

**Comment by PikachuEXE** [comment]
@plentz What I can do/run to make sure the model created actually causes the exception?
Run spec?

**Comment by plentz** [comment]
@PikachuEXE yup. `bundle install && bundle exec rspec spec`

**Comment by PikachuEXE** [comment]
See #47

**Comment by plentz** [comment]
thanks to @PikachuEXE, now we have a *way better* test suite, testing against ruby 2.0,2.1,2.2 and ruby-head, and against a the main rails versions. It's a lot better to find the problems right now - and most of then are related to which version of rails that is being used

**Comment by plentz** [comment]
@vraravam @wpp @midwire @chetanbissa27 @MrHubble @Radsbhatt @amnesia7 @szeryf please, test lol_dba `1.6.7`, it should be fixed :)

@PikachuEXE thanks again, you rock :)

**Comment by amnesia7** [comment]
@plentz sorry but I've tried `1.6.7` and it still doesn't work for me. I'm using rails `4.1.9`

My issue may be slightly more complex than some because my `has_many` are actually for polymorphic tables:

```
class Task < ActiveRecord::Base
  belongs_to :project
  has_many :taggings, :through => :project
  has_many :tags, :through => :taggings
...

class Project < ActiveRecord::Base
  belongs_to :user
  has_many :favourites, :as => :favourable
  acts_as_taggable
...
```
(using `acts_as_taggable_on` gem) causes:
```
Class: Task
Association type: has_many
Association options: {:through=>:project}
Exception: undefined method `options' for nil:NilClass
```
Another example I have is user favourites:
```
class User < ActiveRecord::Base
  has_many :projects
  has_many :favourites
  has_many :favourite_projects, :through =>  :favourites, :source => :favourable, :source_type => "Project"
...

class Favourite < ActiveRecord::Base
  belongs_to :user
  belongs_to :favourable, :polymorphic => true
...
```
which causes:
```
Class: User
Association type: has_many
Association options: {:through=>:favourites, :source=>:favourable, :source_type=>"Project"}
Exception: uninitialized constant Favourite::Favourable
```
I've tried to include just the relevant code but let me know if there's anything else you need to know.

**Comment by plentz** [comment]
@amnesia7 if you can create a pull request creating model classes that causes your problem(without - using acts_as_taggable_on - here https://github.com/plentz/lol_dba/tree/master/spec/fixtures it would be awesome). With that it will be a lot easier to fix the problem and ensure that it will not happen in the future. The stacktrace can be helpfull as well.

**Comment by PikachuEXE** [comment]
I got similar error message about `options` as well
I don't have `acts_as_taggable_on` gem

I don't have to time to try to reproduce it until Friday :S

**Comment by plentz** [comment]
I already saw that rails 4.2(for some reason) generate less wrong indexes (#49)

**Comment by amnesia7** [comment]
@plentz just a quick message to let you know that I've not forgotten about the pull request that you've asked for; I've just not had time to do it yet...

**Comment by plentz** [comment]
@amnesia7 awesome. take your time :)

**Comment by amnesia7** [comment]
@plentz hopefully https://github.com/plentz/lol_dba/pull/58 should be right for polymorphic-has-many-through.

**Comment by DrMavenRebe** [comment]
++

**Comment by klaut** [comment]
Having the same problem.
+1

**Comment by plentz** [comment]
hey guys! I think it's fixed(finally!). can you give a try to 2.0.1 and say if it's ok? :dancers:

**Comment by amnesia7** [comment]
@plentz I'm not sure that it's fixed because I've updated to 2.0.1 and run the `db:find_indexes` and got the following:
```
Some errors here:
Please, create an issue with the following information here https://github.com/plentz/lol_dba/issues:
***************************
Class: User
Association type: has_many
Association options: {:through=>:favourites, :source=>:favourable, :source_type=>"Project"}
Exception: uninitialized constant Favourite::Favourable
/home/me/.rvm/gems/ruby-2.0.0-p643@me/gems/activerecord-4.1.10/lib/active_record/inheritance.rb:133:in `compute_type'
/home/me/.rvm/gems/ruby-2.0.0-p643@me/gems/activerecord-4.1.10/lib/active_record/reflection.rb:221:in `klass'
/home/me/.rvm/gems/ruby-2.0.0-p643@me/gems/lol_dba-2.0.1/lib/lol_dba.rb:125:in `block (2 levels) in check_for_indexes'
/home/me/.rvm/gems/ruby-2.0.0-p643@me/gems/lol_dba-2.0.1/lib/lol_dba.rb:92:in `each_pair'
/home/me/.rvm/gems/ruby-2.0.0-p643@me/gems/lol_dba-2.0.1/lib/lol_dba.rb:92:in `block in check_for_indexes'
/home/me/.rvm/gems/ruby-2.0.0-p643@me/gems/lol_dba-2.0.1/lib/lol_dba.rb:86:in `each'
/home/me/.rvm/gems/ruby-2.0.0-p643@me/gems/lol_dba-2.0.1/lib/lol_dba.rb:86:in `check_for_indexes'
/home/me/.rvm/gems/ruby-2.0.0-p643@me/gems/lol_dba-2.0.1/lib/lol_dba.rb:179:in `simple_migration'
/home/me/.rvm/gems/ruby-2.0.0-p643@me/gems/lol_dba-2.0.1/lib/tasks/lol_dba.rake:7:in `block (2 levels) in <top (required)>'
/home/me/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/rake/task.rb:228:in `call'
/home/me/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/rake/task.rb:228:in `block in execute'
/home/me/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/rake/task.rb:223:in `each'
/home/me/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/rake/task.rb:223:in `execute'
/home/me/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/rake/task.rb:166:in `block in invoke_with_call_chain'
/home/me/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/home/me/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/rake/task.rb:159:in `invoke_with_call_chain'
/home/me/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/rake/task.rb:152:in `invoke'
/home/me/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/rake/application.rb:143:in `invoke_task'
/home/me/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/rake/application.rb:101:in `block (2 levels) in top_level'
/home/me/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/rake/application.rb:101:in `each'
/home/me/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/rake/application.rb:101:in `block in top_level'
/home/me/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/rake/application.rb:110:in `run_with_threads'
/home/me/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/rake/application.rb:95:in `top_level'
/home/me/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/rake/application.rb:73:in `block in run'
/home/me/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/rake/application.rb:160:in `standard_exception_handling'
/home/me/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/rake/application.rb:70:in `run'
bin/rake:4:in `<main>'
```
Any ideas what could've happened here?

**Comment by plentz** [comment]
@vraravam @wpp @midwire @chetanbissa27 @MrHubble @Radsbhatt @amnesia7 @szeryf @PikachuEXE @DrMavenRebe @klaut yeah, finally I think that I nailed it in version `2.1.1`. can you guys give it a shot?

huge props to @amnesia7 for the PR(#58) with a scenario of this bug and for @lowjoel for giving me a hint of how to solve this @ #63.

**Comment by wpp** [comment]
Seems to work on my side. Get the error on 1.6.4, works as expected in 2.1.1. Thanks @plentz

**Comment by amnesia7** [comment]
Might be worth waiting to see if there's any other feedback about this version but I'm not sure it has worked for me.

The error has gone that was being thrown in the terminal when running `bin/rake db:find_indexes` but the indexes being offered don't seem right.

For instance, one is (where thing is favourable):
```
add_index :favourites, [:thing_id, :user_id]
```
but the actual fields on the model are:
```
class Favourite < ActiveRecord::Base
  belongs_to :user
  belongs_to :favourable, polymorphic: true
```
so I was expecting something more like:
```
add_index :favourites, [:favourable_id, :favourable_type, :user_id]
```
in this case.

Am I missing something?

I tried running `bundle show | grep lol_dba` and it only shows `* lol_dba (2.1.1)`

**Comment by plentz** [comment]
@amnesia7 no, you're right :)

We still have a problem with `has_many` generating inexistent indexes in a few cases (the one I will try to fix @ `has_many_fix` branch). I already added a failing test case here https://github.com/plentz/lol_dba/commit/bf9c4eb7124d3f998d6cf65ffb3165a2068b4335#diff-d90d1bc62234f746df962016d75e56c8R58. I've created the issue  #76 to deal with it

**Comment by amnesia7** [comment]
Thanks @plentz , just let me know if you need me to test anything.
