### ISSUE TITLE
Polymorphic associations with explicit source trips lol_dba

### ISSUE THREAD

**Issue by lowjoel** [plentz/lol_dba#63]
Hi there, I'm a developer on Coursemology (repo: Coursemology/Coursemology2), and I'm setting up lol_dba. Running db:find_indexes fails:

```
Class: Course::Assessment::Submission
Association type: has_many
Association options: {:through=>:answers, :source=>:actable, :source_type=>"Course::Assessment::Answer::MultipleResponse"}
Exception: uninitialized constant Course::Assessment::Answer::Actable
D:/Development/Projects/Coursemology/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/inheritance.rb:158:in `compute_type'
D:/Development/Projects/Coursemology/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/reflection.rb:271:in `compute_class'
D:/Development/Projects/Coursemology/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/reflection.rb:267:in `klass'
D:/Development/Projects/Coursemology/vendor/bundle/ruby/2.2.0/gems/lol_dba-2.0.0/lib/lol_dba.rb:125:in `block (2 levels) in check_for_indexes'
D:/Development/Projects/Coursemology/vendor/bundle/ruby/2.2.0/gems/lol_dba-2.0.0/lib/lol_dba.rb:92:in `each_pair'
D:/Development/Projects/Coursemology/vendor/bundle/ruby/2.2.0/gems/lol_dba-2.0.0/lib/lol_dba.rb:92:in `block in check_for_indexes'
D:/Development/Projects/Coursemology/vendor/bundle/ruby/2.2.0/gems/lol_dba-2.0.0/lib/lol_dba.rb:86:in `each'
D:/Development/Projects/Coursemology/vendor/bundle/ruby/2.2.0/gems/lol_dba-2.0.0/lib/lol_dba.rb:86:in `check_for_indexes'
D:/Development/Projects/Coursemology/vendor/bundle/ruby/2.2.0/gems/lol_dba-2.0.0/lib/lol_dba.rb:179:in `simple_migration'
D:/Development/Projects/Coursemology/vendor/bundle/ruby/2.2.0/gems/lol_dba-2.0.0/lib/tasks/lol_dba.rake:7:in `block (2 levels) in <top (required)>'
```

Probably because we're using somewhat exotic options, in part due to the hzamani/activerecord-acts_as gem.

**Comment by plentz** [comment]
Thanks for the report - patches are welcome :dancers:

**Comment by plentz** [comment]
btw, holly molly. what a weird situation. can you test using 2.0.1 that I just released?

**Comment by lowjoel** [comment]
No banana, still getting the same thing:

Class: Course
Association type: has_many
Association options: {:through=>:lesson_plan_items, :source=>:actable, :source_type=>"Course::LessonPlan::Event"}
Exception: uninitialized constant Course::LessonPlan::Item::Actable
D:/Development/Projects/Coursemology/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/inheritance.rb:158:in `compute_type'
D:/Development/Projects/Coursemology/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/reflection.rb:271:in `compute_class'
D:/Development/Projects/Coursemology/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/reflection.rb:267:in `klass'
D:/Development/Projects/Coursemology/vendor/bundle/ruby/2.2.0/gems/lol_dba-2.0.1/lib/lol_dba.rb:125:in `block (2 levels) in check_for_indexes'
D:/Development/Projects/Coursemology/vendor/bundle/ruby/2.2.0/gems/lol_dba-2.0.1/lib/lol_dba.rb:92:in `each_pair'
D:/Development/Projects/Coursemology/vendor/bundle/ruby/2.2.0/gems/lol_dba-2.0.1/lib/lol_dba.rb:92:in `block in check_for_indexes'
D:/Development/Projects/Coursemology/vendor/bundle/ruby/2.2.0/gems/lol_dba-2.0.1/lib/lol_dba.rb:86:in `each'
D:/Development/Projects/Coursemology/vendor/bundle/ruby/2.2.0/gems/lol_dba-2.0.1/lib/lol_dba.rb:86:in `check_for_indexes'
D:/Development/Projects/Coursemology/vendor/bundle/ruby/2.2.0/gems/lol_dba-2.0.1/lib/lol_dba.rb:179:in `simple_migration'
D:/Development/Projects/Coursemology/vendor/bundle/ruby/2.2.0/gems/lol_dba-2.0.1/lib/tasks/lol_dba.rake:7:in `block (2 levels) in <top (required)>'

**Comment by plentz** [comment]
@lowjoel well can you create a PR just with the model that causes the problem?

**Comment by lowjoel** [comment]
I am guessing that source_type isn't being adhered to. I'll probably go dig into the stack trace.

**Comment by lowjoel** [comment]
It does seem to be a shorter list of errors, though...

**Comment by lowjoel** [comment]
I think this is the problem.

When you see a has_many through, the code assumes that the intermediate relation is a has_many. In my case, the intermediate relation is a polymorphic belongs_to. So it's a has_many because of the first relation, not the through the relation.

`through_class.reflections.stringify_keys[source.to_s]` will return the belongs_to relation, and since it's polymorphic, there can not be a class associated. the `#klass` call thus fails. `reflection_options` does contain the type in this case, it's the `source_type` option, which should be used in this circumstance for AR to form a correct query.

**Comment by lowjoel** [comment]
I changed the block in lol_dba.rb:124 to this:

```ruby
            if source = reflection_options.options[:source]
              association_reflection = through_class.reflections.stringify_keys[source.to_s]
              association_class = association_reflection.options[:polymorphic] ?
                reflection_options.options[:source_type].constantize : association_reflection.klass
              association_foreign_key = get_through_foreign_key(association_class, reflection_options)
            elsif through_reflections = through_class.reflections.stringify_keys[reflection_name.singularize]
```

**Comment by plentz** [comment]
@lowjoel I was doing something almost identical. Can you point your Gemfile to `https://github.com/plentz/lol_dba/tree/issue_63` and see if it's working?

**Comment by lowjoel** [comment]
The branch doesn't work. The crucial fix is this line:

```ruby
              association_class = association_reflection.options[:polymorphic] ?
                reflection_options.options[:source_type].constantize : association_reflection.klass
```

In the branch you pushed, it would use the relation as the association name, which is not what `source_type` is. `source_type` is the name of the model (in my case Course::LessonPlan::Event) to use, not the name of the association. So `through_class.reflections.stringify_keys[source.to_s]` returns nil now.

**Comment by plentz** [comment]
@lowjoel sorry for taking so long to reply. the gem was kind of dormant and now I'm back :)

I've released 2.1 which fix a few things, but not this one. I've created the branch `issue_63` with the changes you proposed and it looks like everything still works. can you help me creating a test case that doesn't work with the previous code and work with the current one?

**Comment by plentz** [comment]
fixed by 594aea5 (version `2.1.1`). thanks a lot 😄
