### ISSUE TITLE
table does not exist

### ISSUE THREAD

**Issue by RST-J** [plentz/lol_dba#67]
Unfortunately there is no more output there which I could provide.
If you give me a hint, I'll look into the details.

I suspect there is some problem with `has_many through:` associations, maybe in combination with STI, as Team is a subclass of another model.

**Comment by plentz** [comment]
Hi @RST-J, sorry for taking so long to reply. I just released 2.1 which I think fixes this problem. Since it was so long ago, I think that you can't even test the same scenario, but if you can, please reopen the issue and we can work together to find a fix for this :)

**Comment by RST-J** [comment]
The problem still exists. In the meantime I probably got a better understanding about reflections and relations at all - I'll try to come up with a MWE or maybe even a fix.
